#!/usr/bin/env python3
"""Train huajiao oil-content model on processed spectra.

This script trains a PLSR model (optionally with GA wavelength selection) to
predict ``oil_ml_per_100g`` from ROI-aggregated spectra.

It is designed to work with datasets generated by:
  - scripts/build_huajiao_from_split.py (using refined ROI masks)
"""

from __future__ import annotations

import argparse
import json
import sys
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import List, Optional, Sequence

import numpy as np
import pandas as pd
from sklearn.cross_decomposition import PLSRegression
from sklearn.metrics import mean_absolute_error, r2_score, root_mean_squared_error
from sklearn.model_selection import KFold

# Ensure local src is importable when running directly.
repo_root = Path(__file__).resolve().parent.parent
src_path = repo_root / "src"
if src_path.exists():
    sys.path.insert(0, str(src_path))

from oil_content_detection.feature_selection.ga_selector import GAConfig, GeneticAlgorithmSelector  # noqa: E402
from oil_content_detection.preprocessing import PreprocessStep, apply_preprocessing_pipeline  # noqa: E402
from oil_content_detection.utils import get_logger, save_model, save_results_json, save_wavelengths, setup_single_thread  # noqa: E402

setup_single_thread()
logger = get_logger(__name__)


@dataclass(frozen=True)
class TrainConfig:
    train_spectra: Path
    val_spectra: Path
    target: str
    preprocess: List[PreprocessStep]
    use_ga: bool
    ga_config: GAConfig
    n_components_max: int
    cv_splits: int
    seed: int
    output_dir: Path
    save_model_file: bool


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Train huajiao oil content (ml/100g) prediction model")
    parser.add_argument(
        "--train-spectra",
        type=Path,
        default=Path("data/processed/huajiao_refined/train/huajiao_spectra.parquet"),
    )
    parser.add_argument(
        "--val-spectra",
        type=Path,
        default=Path("data/processed/huajiao_refined/val/huajiao_spectra.parquet"),
    )
    parser.add_argument("--target", type=str, default="oil_ml_per_100g", help="Target column name")
    parser.add_argument(
        "--preprocess",
        nargs="*",
        default=["sg1"],
        help="Preprocess steps: raw | snv | msc | normalize | detrend | sg | sg1 (SG deriv=1)",
    )
    parser.add_argument("--sg-window", type=int, default=13, help="Savitzky-Golay window_length (odd)")
    parser.add_argument("--sg-polyorder", type=int, default=2, help="Savitzky-Golay polyorder")
    parser.add_argument("--no-ga", action="store_true", help="Disable GA wavelength selection (use full bands)")

    # GA params
    parser.add_argument("--ga-pop", type=int, default=20, help="GA population size")
    parser.add_argument("--ga-gen", type=int, default=20, help="GA generations")
    parser.add_argument("--ga-min", type=int, default=5, help="GA min features")
    parser.add_argument("--ga-max", type=int, default=30, help="GA max features")
    parser.add_argument("--ga-target", type=int, default=18, help="GA target features (soft constraint)")
    parser.add_argument("--ga-cv", type=int, default=5, help="GA CV folds (R² as fitness)")
    parser.add_argument("--ga-patience", type=int, default=6, help="GA early-stopping patience")
    parser.add_argument("--ga-mutation", type=float, default=0.04, help="GA mutation rate")
    parser.add_argument("--ga-crossover", type=float, default=0.85, help="GA crossover rate")
    parser.add_argument("--ga-elite", type=int, default=2, help="GA elite count")
    parser.add_argument("--seed", type=int, default=2026, help="Random seed")

    parser.add_argument("--cv-splits", type=int, default=5, help="CV folds for n_components selection")
    parser.add_argument("--max-components", type=int, default=10, help="Max PLSR components")
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("results/huajiao_refined_oil_content_20260104"),
        help="Directory to save training outputs",
    )
    parser.add_argument("--no-save-model", action="store_true", help="Do not save model.pkl")
    parser.add_argument("--verbose", action="store_true", help="Verbose GA progress")
    return parser.parse_args()


def _load_df(path: Path) -> pd.DataFrame:
    if path.exists():
        return pd.read_parquet(path)
    csv_path = path.with_suffix(".csv")
    if csv_path.exists():
        return pd.read_csv(csv_path)
    raise FileNotFoundError(f"Spectra file not found: {path} (or {csv_path})")


def _wl_cols(df: pd.DataFrame) -> List[str]:
    cols = [c for c in df.columns if c.startswith("wl_")]
    if not cols:
        raise ValueError("No wl_ columns found in spectra table")
    return cols


def _parse_preprocess(args: argparse.Namespace) -> List[PreprocessStep]:
    steps: List[PreprocessStep] = []
    for raw in args.preprocess:
        name = str(raw).strip().lower()
        if not name or name == "raw":
            continue
        if name in {"sg", "savgol"}:
            steps.append(
                PreprocessStep(
                    name="sg",
                    params={
                        "window_length": int(args.sg_window),
                        "polyorder": int(args.sg_polyorder),
                        "deriv": 0,
                    },
                )
            )
        elif name in {"sg1", "sg_1st", "sg-1"}:
            steps.append(
                PreprocessStep(
                    name="sg",
                    params={
                        "window_length": int(args.sg_window),
                        "polyorder": int(args.sg_polyorder),
                        "deriv": 1,
                    },
                )
            )
        elif name in {"snv", "msc", "normalize", "detrend"}:
            steps.append(PreprocessStep(name=name))
        else:
            raise ValueError(f"Unknown preprocess step: {raw}")
    return steps


def _choose_n_components(X: np.ndarray, y: np.ndarray, max_components: int, cv_splits: int, seed: int) -> int:
    max_components = int(min(max_components, X.shape[1], max(1, len(y) - 1)))
    if max_components <= 1:
        return 1

    cv = KFold(n_splits=cv_splits, shuffle=True, random_state=seed)
    best_n = 1
    best_rmse = float("inf")

    for n in range(1, max_components + 1):
        model = PLSRegression(n_components=n, scale=False)
        rmses: List[float] = []
        for train_idx, test_idx in cv.split(X):
            model.fit(X[train_idx], y[train_idx])
            pred = model.predict(X[test_idx]).ravel()
            rmses.append(root_mean_squared_error(y[test_idx], pred))
        rmse = float(np.mean(rmses))
        if rmse < best_rmse:
            best_rmse = rmse
            best_n = n

    return int(best_n)


def _wavelengths_from_cols(cols: Sequence[str]) -> List[int]:
    out: List[int] = []
    for c in cols:
        try:
            out.append(int(c.split("_", 1)[1]))
        except Exception:
            out.append(-1)
    return out


def _build_prediction_table(
    df: pd.DataFrame,
    y_true: np.ndarray,
    y_pred: np.ndarray,
    *,
    target: str,
) -> pd.DataFrame:
    true_col = f"{target}_true"
    pred_col = f"{target}_pred"
    out = pd.DataFrame(
        {
            "sample_id": df["sample_id"].astype(str).to_numpy() if "sample_id" in df.columns else np.arange(len(y_true)),
            "sample_id_raw": df["sample_id_raw"].astype(str).to_numpy() if "sample_id_raw" in df.columns else "",
            true_col: y_true,
            pred_col: y_pred,
        }
    )
    out["error"] = out[pred_col] - out[true_col]
    out["abs_error"] = out["error"].abs()

    denom = out[true_col].abs()
    out["relative_error_percent"] = np.where(denom > 0, out["error"] / denom * 100.0, np.nan)
    out["abs_relative_error_percent"] = np.where(denom > 0, out["abs_error"] / denom * 100.0, np.nan)

    for col in ["weight_g", "distill_ml", "pixel_count", "valid_pixel_count", "coverage_ratio"]:
        if col in df.columns and col not in out.columns:
            out[col] = df[col].to_numpy()
    return out


def main() -> None:
    args = parse_args()
    train_df = _load_df(args.train_spectra)
    val_df = _load_df(args.val_spectra)

    wl_cols = _wl_cols(train_df)
    if args.target not in train_df.columns or args.target not in val_df.columns:
        raise KeyError(f"Target column missing: {args.target}")

    X_train = train_df[wl_cols].to_numpy(dtype=float)
    y_train = train_df[args.target].to_numpy(dtype=float)
    X_val = val_df[wl_cols].to_numpy(dtype=float)
    y_val = val_df[args.target].to_numpy(dtype=float)

    preprocess_steps = _parse_preprocess(args)
    X_train = apply_preprocessing_pipeline(X_train, preprocess_steps)
    X_val = apply_preprocessing_pipeline(X_val, preprocess_steps)

    wavelengths = _wavelengths_from_cols(wl_cols)

    ga_cfg = GAConfig(
        population_size=int(args.ga_pop),
        generations=int(args.ga_gen),
        crossover_rate=float(args.ga_crossover),
        mutation_rate=float(args.ga_mutation),
        elite_count=int(args.ga_elite),
        min_features=int(args.ga_min),
        max_features=int(args.ga_max),
        target_features=int(args.ga_target),
        random_state=int(args.seed),
        cv_splits=int(args.ga_cv),
        patience=int(args.ga_patience),
        verbose=bool(args.verbose),
    )

    support = np.ones(X_train.shape[1], dtype=bool)
    selected_wavelengths: List[int] = wavelengths
    ga_score: Optional[float] = None
    ga_history: Optional[list[dict]] = None

    use_ga = not args.no_ga
    if use_ga:
        logger.info(
            "Running GA: pop=%d gen=%d features=%d..%d target=%d cv=%d",
            ga_cfg.population_size,
            ga_cfg.generations,
            ga_cfg.min_features,
            ga_cfg.max_features,
            ga_cfg.target_features,
            ga_cfg.cv_splits,
        )
        selector = GeneticAlgorithmSelector(ga_cfg)
        selector.fit(X_train, y_train)
        support = selector.get_support()
        selected_wavelengths = [wavelengths[i] for i in selector.selected_indices()]
        ga_score = float(selector.best_score())
        ga_history = selector.history()
        logger.info("GA selected %d wavelengths (best CV score=%.4f)", len(selected_wavelengths), ga_score)

    X_train_sel = X_train[:, support]
    X_val_sel = X_val[:, support]

    n_components = _choose_n_components(
        X_train_sel,
        y_train,
        max_components=int(args.max_components),
        cv_splits=int(args.cv_splits),
        seed=int(args.seed),
    )
    logger.info("Training PLSR: n_components=%d, n_features=%d", n_components, X_train_sel.shape[1])

    model = PLSRegression(n_components=n_components, scale=False)
    model.fit(X_train_sel, y_train)

    train_pred = model.predict(X_train_sel).ravel()
    val_pred = model.predict(X_val_sel).ravel()

    metrics = {
        "train": {
            "n": int(len(y_train)),
            "r2": float(r2_score(y_train, train_pred)),
            "rmse": float(root_mean_squared_error(y_train, train_pred)),
            "mae": float(mean_absolute_error(y_train, train_pred)),
        },
        "val": {
            "n": int(len(y_val)),
            "r2": float(r2_score(y_val, val_pred)),
            "rmse": float(root_mean_squared_error(y_val, val_pred)),
            "mae": float(mean_absolute_error(y_val, val_pred)),
        },
    }

    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    # Save per-sample predictions (with IDs + error metrics)
    train_pred_df = _build_prediction_table(train_df, y_train, train_pred, target=args.target)
    val_pred_df = _build_prediction_table(val_df, y_val, val_pred, target=args.target)
    train_pred_df.to_csv(output_dir / "train_predictions.csv", index=False)
    val_pred_df.to_csv(output_dir / "val_predictions.csv", index=False)
    train_pred_df.sort_values("abs_error", ascending=False).to_csv(
        output_dir / "train_predictions_sorted_by_abs_error.csv", index=False
    )
    val_pred_df.sort_values("abs_error", ascending=False).to_csv(
        output_dir / "val_predictions_sorted_by_abs_error.csv", index=False
    )
    pd.concat(
        [
            train_pred_df.assign(split="train"),
            val_pred_df.assign(split="val"),
        ],
        ignore_index=True,
    ).to_csv(output_dir / "predictions_all.csv", index=False)

    # Save support / wavelengths
    np.save(output_dir / "feature_support.npy", support)
    save_wavelengths([int(x) for x in selected_wavelengths], output_dir / "selected_wavelengths.json")

    if ga_history is not None:
        from oil_content_detection.utils.io import _convert_to_serializable

        with (output_dir / "ga_history.json").open("w", encoding="utf-8") as f:
            json.dump(_convert_to_serializable(ga_history), f, indent=2, ensure_ascii=False)

    if args.verbose:
        print("\n=== Metrics ===")
        print(json.dumps(metrics, indent=2, ensure_ascii=False))

    result_payload = {
        "target": args.target,
        "wl_count": int(len(wl_cols)),
        "use_ga": bool(use_ga),
        "selected_wavelength_count": int(int(support.sum())),
        "selected_wavelengths": [int(x) for x in selected_wavelengths],
        "ga_score": ga_score,
        "preprocess": [asdict(s) for s in preprocess_steps],
        "n_components": int(n_components),
        "metrics": metrics,
        "train_spectra": str(args.train_spectra),
        "val_spectra": str(args.val_spectra),
    }
    save_results_json(result_payload, output_dir / "results.json", include_timestamp=False)

    if not args.no_save_model:
        save_model(model, output_dir / "plsr_model.pkl")

    print("=== Huajiao Oil Content Training Result ===")
    print(f"Output: {output_dir}")
    print(f"Target: {args.target}")
    print(f"Preprocess: {[s.name for s in preprocess_steps] or ['raw']}")
    print(f"Use GA: {use_ga} (selected {int(support.sum())} / {len(wl_cols)} wavelengths)")
    if ga_score is not None:
        print(f"GA best CV score: {ga_score:.4f}")
    print(f"PLSR components: {n_components}")
    print(f"Train: R²={metrics['train']['r2']:.4f}, RMSE={metrics['train']['rmse']:.4f}, MAE={metrics['train']['mae']:.4f}")
    print(f"Val:   R²={metrics['val']['r2']:.4f}, RMSE={metrics['val']['rmse']:.4f}, MAE={metrics['val']['mae']:.4f}")


if __name__ == "__main__":
    main()
